### PR TITLE
Format whitespace

### PR DESCRIPTION
**Pull request by thaliaarchi**
There's a *lot* of trailing whitespace and some files have CRLF line endings. This normalizes such whitespace, so that diffs between chapters are consistent.

### CODE REVIEW

**Comment by XmiliaH** [comment]
Double space at the end of a line in markdown is significant and will preserve the newline. WIthout the spaces the newline will be stripped.

**Comment by thaliaarchi** [comment]
These five files have the only potentially-semantic trailing spaces:

- README.md: [1 potentially intentional line break](https://github.com/SeaOfNodes/Simple/blob/main/README.md?plain=1#L9). I think it reads better without the line break, as it interrupts a paragraph.
- chapter05/README.md: all unintentional
- chapter06/README.md: all unintentional
- chapter09/README.md: all unintentional
- chapter10/README.md: [1 potentially intentional line break](https://github.com/SeaOfNodes/Simple/blob/main/chapter10/README.md?plain=1#L164). Although it's before a bulleted list, this sentence does not set off the list, so I think it was unintentional, especially as there is single trailing space after the next sentence.

(Identified with `rg --glob '*.md' --glob !'*-grammar.md' '[^ \t][ \t]{2,}$'`.)

I think these are all spurious.

**Comment by XmiliaH** [comment]
The ch10 one is https://github.com/SeaOfNodes/Simple/blame/a749c244bea3e2774d453165cbd18ed52863a8f5/chapter10/README.md#L163.

For all but the two mentiond cases I agree that they are unintentional.

@cliffclick @dibyendumajumdar Are you aware that double spaces preserve the newline and used it here intentional or can they be removed?

**Comment by dibyendumajumdar** [comment]
Thanks @thaliaarchi  @XmiliaH  - I am not aware of the subtleties of markdown sadly - I remember you helped me fix some issues before @XmiliaH 

Assume we are good to merge this?

**Review by dibyendumajumdar — APPROVED** [review]

**Pull request merged**
