### PR TITLE
Ch14 - narrow int&flt types

### PR DESCRIPTION
**Pull request by cliffclick**
A prelude to arrays, this allows Simple to parse and manipulate narrow integer and float types, rounding/truncating when assigned, and assumed to be probably extended when loaded from a narrow struct field.

### CODE REVIEW

**Comment by XmiliaH** [comment]
Narrowing for
```cpp
u8 b = 123;
while(b) b = b + 456;// Truncate
return b;
```
seems not to work

**Comment by thaliaarchi** [comment]
Design questions:

- The wording of the chapter README suggests that floats are rounded when truncated or sign-extended. For `f32`, why not zero-extend to `u64`?
- Why is there `flt` and `f64`, `int` and `i64`, and `u1` and `bool`? Why is there no `u64`?

In reviewing the changes made to the parser, I've found these issues. Not all are
from this chapter. I have fixed the marked bugs locally.

- [x] The grammar file has not been updated.
- [ ] The grammar includes `|` and `^` bitwise ops, but only `&` is parsed. Should those be removed from the grammar or should `OrNode` and `XorNode` be added?
- [x] `>>` is parsed before `>>>`, making `>>>` impossible.
- [ ] Assignment is allowed as an expression.
- [ ] Issues parsing `?` in `Parser#type`: Forward reference types don't work with
  `?`, because it forces the caller to reparse the type. `?` is only used with
  structs, but the parser still accepts it otherwise.
- [ ] Should the change to `Parser#parseStruct`, making it return the following
  expression, be backported?

I've only reviewed the parser so far.

**Comment by cliffclick** [comment]
Not sure what you're asking about for `f32` rounding.
`flt,f64` and `int,i64` and `u1,bool` are all synonyms.  No `u64` because its functionally the same as `i64` but hints at some other unsigned difference.  I can be talked into adding it.
Adding Or,Xor.
Fixed parsing `>>>`
Assignment IS allowed as an expression, on purpose.
Test Chapter13Test.testForwardRef exactly checks this?
```
struct S1 { S2? s; }
struct S2 { int x; }
return new S1.s=new S2;
```

**Comment by thaliaarchi** [comment]
These snippets fail, because struct forward references are not handled for *declarations*.

```c++
S x = new S;
struct S { int x; }
return x;
```
```c++
S? x = new S;
struct S { int x; }
return x;
```

**Comment by cliffclick** [comment]
Disallowed (for now).  Quality of implementation issue; we'd have to rework fairly substantially how we compute aliases.
User is forced to move the decl up
```java
struct S { int x; }
S x = new S;
return x;
```

**Review by thaliaarchi — APPROVED** [review]

**Pull request merged**
