### PR TITLE
Bail out unclosed block

### PR DESCRIPTION
**Pull request by oraluben**

### CODE REVIEW

**Comment by dibyendumajumdar** [comment]
thank you

**Comment by dibyendumajumdar** [comment]
btw this breaks many of the tests, because we parse the main program as a block too, and that doesn't have a closing }
That was the reason why we check EOF or }

**Comment by oraluben** [comment]
> btw this breaks many of the tests

Oh I didn't run a full test locally, I'll try to run and fix.

**Comment by XmiliaH** [comment]
I think it would be nice if this fix could also handle `return 1;}invalid`

**Comment by oraluben** [comment]
> I think it would be nice if this fix could also handle `return 1;}invalid`

Nice catch! Fixed.

**Review by dibyendumajumdar — APPROVED** [review]

**Comment by cliffclick** [comment]
Thanks for the fix!  In the future, please do not add flags to the parser's structure.  Nearly always we can fix parser issues by adding/removing/moving the actual parse logic up and down the grammar.  In this case all we needed was a `require(parseBlock(),"}")` instead of a complex change & flag to parseBlock itself.  

Probably the issue stems from allowing top-level programs to not have `{}` such as `return 1+2;` being valid.  This is because we do not parse any function headers yet - so we're calling parseBlock without having `{}`, so parseBlock shouldn't parse `{}` and parsing the curly braces becomes responsibility of the parseBlock caller.  Its an odd convention, fixed when we parse function headers in a future chapter.

**Pull request merged**
