### PR TITLE
don't call peephole on node returned from idealize

### PR DESCRIPTION
**Pull request by RobertObkircher**

### CODE REVIEW

**Comment by XmiliaH** [comment]
I think that case should even be moved into `compute`.

**Comment by RobertObkircher** [comment]
Right, compute already does that. I guess it can also be removed from `CProjNode` in future chapters.

**Comment by RobertObkircher** [comment]
A potential problem with this change is that peephole now replaces with a `new XCtrlNode()` instead of `Parser.XCTRL;`

**Comment by cliffclick** [comment]
Minor inefficiency: "new XCtrlNode().peephole()" will return "Parser.XCTRL" after making the Node then GVN'ing it.

**Review by cliffclick — APPROVED** [review]
Looks good!

**Pull request merged**
