### PR TITLE
Update JDK to 21

### PR DESCRIPTION
**Pull request by oraluben**
Current config (target 20 and with `--enable-preview`) have issue with newer JDK version (e.g. latest LTS, 21, see [error](https://github.com/oraluben/Simple/actions/runs/6717620743/job/18255815060)). Since this project use new Java features, I suggest to switch to JDK 21 and remove the preview option.

PS: I noticed the previous bump was made at the exact day when JDK 21 release :)

Other changes in this pull request:
1. Add cache to CI's maven;
2. fix a pom issue and fix runtime warning for antlr;
3. enable CI for each pull request.

### CODE REVIEW

**Comment by dibyendumajumdar** [comment]
Thank you - I am good with this, will wait for @cliffclick  and @XmiliaH to opine

**Comment by XmiliaH** [comment]
I would like to see this merged. I always need to change it locally.

**Comment by oraluben** [comment]
Other changes in this pull request:
1. Add cache to CI's maven;
2. fix a pom issue and fix runtime warning for antlr;
3. enable CI for each pull request.

**Comment by dibyendumajumdar** [comment]
Please could you direct the PR to chapter5?

**Pull request merged**
